version: '3'
services:
  link_shortener:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app.env
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    container_name: "redis"
    image: redis:7.2
    ports:
      - "6379:6379"

  nginx:
    container_name: "nginx"
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - link_shortener